name: Terraform Provisioning
on:
  push:
    paths:
        - terraform/**
  workflow_dispatch:

env:
    MONDOO_CONFIG_BASE64: ${{ secrets.MONDOO_CONFIG_BASE64 }}

jobs:
  terraform-pre-plan-validation:
    name: "Terraform Validate"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    defaults:
      run:
        working-directory: ./terraform
        
    steps:
      - uses: 'actions/checkout@v3'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-2

      - uses: hashicorp/setup-terraform@v2
        with:
            terraform_wrapper: false
    
      - name: Terraform Init
        id: init
        run: terraform init -reconfigure
    
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check  
    
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color